export const GOLD = '#D4AF37'
export const SECONDARY = '#3b3'

// export const PURPLE = '#6a197d'
// export const PINK = '#ffa5b0'
// export const GREY = '#e0dede'
// export const LIGHT_GREY = '#f5f5f5'
// export const COMPLEMENT_GREEN = '#2C7D19'
// export const PAPER = '#F7DCFD'
// export const TEXT_GREY = '#C4C4C4'

export const PURPLE = '#6a197d'
export const PINK = '#6312ff'
export const GREY = '#e0dede'
export const LIGHT_GREY = '#f5f5f5'
export const COMPLEMENT_GREEN = '#2C7D19'
export const PAPER = '#f7f7f7'
export const TEXT_GREY = '#C4C4C4'
